"""
Allomorph - Configuration & Instrument/Voice Registry Engine.
Provides modular access to physical scales, strings, instruments, target voices, and coil geometry.
"""

from allomorph.config.geometry import (
    _infer_pole_type,
    compute_effective_position,
    resolve_pickup_coils,
    resolve_voice_coils,
    resolve_voice_pickups,
)
from allomorph.config.instruments import (
    INSTRUMENT_ALIASES,
    INSTRUMENTS,
    INSTRUMENTS_DIR,
    get_source_pickup,
    load_all_instruments,
    load_instrument,
)
from allomorph.config.preamps import (
    PREAMPS,
    PREAMPS_FILE,
    get_preamp,
    load_preamps_config,
)
from allomorph.config.scales import (
    CONFIG_DIR,
    REPO_ROOT,
    SCALES,
    SCALES_FILE,
    load_scales,
    resolve_scale_range,
)
from allomorph.config.schema import (
    AllomorphBaseModel,
    CoilConfig,
    InstrumentConfig,
    InstrumentStringsConfig,
    PickupComponentConfig,
    PickupConfig,
    PreampBandConfig,
    PreampConfig,
    PreampOverrideConfig,
    PreampsCatalog,
    ResolvedStringConfig,
    ScaleConfig,
    ScalesCatalog,
    SpiceFloat,
    StringPresetConfig,
    StringsCatalog,
    VoiceCoilConfig,
    VoiceConfig,
    VoicePickupConfig,
    parse_spice_unit,
)
from allomorph.config.strings import (
    STRINGS,
    STRINGS_FILE,
    get_instrument_string,
    get_voice_string,
    load_strings_config,
)
from allomorph.config.voices import (
    VOICES,
    VOICES_DIR,
    VOICES_FILE,
    VoiceRegistry,
    load_voice_config,
    load_voices_config,
)

__all__ = [
    "CONFIG_DIR",
    "INSTRUMENTS",
    "INSTRUMENTS_DIR",
    "INSTRUMENT_ALIASES",
    "PREAMPS",
    "PREAMPS_FILE",
    "REPO_ROOT",
    "SCALES",
    "SCALES_FILE",
    "STRINGS",
    "STRINGS_FILE",
    "VOICES",
    "VOICES_DIR",
    "VOICES_FILE",
    "AllomorphBaseModel",
    "CoilConfig",
    "InstrumentConfig",
    "InstrumentStringsConfig",
    "PickupComponentConfig",
    "PickupConfig",
    "PreampBandConfig",
    "PreampConfig",
    "PreampOverrideConfig",
    "PreampsCatalog",
    "ResolvedStringConfig",
    "ScaleConfig",
    "ScalesCatalog",
    "SpiceFloat",
    "StringPresetConfig",
    "StringsCatalog",
    "VoiceCoilConfig",
    "VoiceConfig",
    "VoicePickupConfig",
    "VoiceRegistry",
    "_infer_pole_type",
    "compute_effective_position",
    "get_instrument_string",
    "get_preamp",
    "get_source_pickup",
    "get_voice_string",
    "load_all_instruments",
    "load_instrument",
    "load_preamps_config",
    "load_scales",
    "load_strings_config",
    "load_voice_config",
    "load_voices_config",
    "parse_spice_unit",
    "resolve_pickup_coils",
    "resolve_scale_range",
    "resolve_voice_coils",
    "resolve_voice_pickups",
]
