"""
Allomorph Physics Engine
Universal spatial acoustics, string dispersion, and transducer deconvolution.
"""

from allomorph.physics.aperture import (
    BODY_COUPLING_PROPERTIES,
    aperture_response,
    compute_body_microphonic_coupling,
    compute_coil_aperture,
    compute_saddle_boundary_coupling,
    get_coil_register,
    is_voice_matching_source,
    numpy_aperture,
    numpy_pickup_acoustic_response,
    numpy_pickup_macro_aperture,
    numpy_position,
    pickup_acoustic_response,
    position_envelope,
)
from allomorph.physics.deconvolution import (
    numpy_pickup_anti_resonance,
    numpy_pickup_electrical_response,
    pickup_anti_resonance,
    pickup_electrical_response,
    resolve_pickup_electrical_deconvolution,
    resolve_pickup_electrical_deconvolution_np,
    resolve_pickup_electrical_response,
    resolve_pickup_electrical_response_np,
)
from allomorph.physics.prefilter import (
    compute_aperture_prefilter_fir,
    compute_voice_prefilter_firs,
)
from allomorph.physics.strings import (
    INHARMONICITY_ANCHORS_BS,
    INHARMONICITY_ANCHORS_F0,
    MEAN_BASS_F0,
    NOTE_NAMES,
    STRING_FUNDAMENTALS,
    compute_differential_longitudinal_transfer,
    compute_differential_string_transfer,
    compute_dispersive_wave_speed,
    generate_wave_speed_continuum,
    get_inharmonicity_for_f0,
    get_voice_string,
    infer_string_names,
    pitch_to_note_name,
    resolve_scale_length,
    resolve_scale_range,
)

__all__ = [
    "BODY_COUPLING_PROPERTIES",
    "INHARMONICITY_ANCHORS_BS",
    "INHARMONICITY_ANCHORS_F0",
    "MEAN_BASS_F0",
    "NOTE_NAMES",
    "STRING_FUNDAMENTALS",
    "aperture_response",
    "compute_aperture_prefilter_fir",
    "compute_body_microphonic_coupling",
    "compute_coil_aperture",
    "compute_differential_longitudinal_transfer",
    "compute_differential_string_transfer",
    "compute_dispersive_wave_speed",
    "compute_saddle_boundary_coupling",
    "compute_voice_prefilter_firs",
    "generate_wave_speed_continuum",
    "get_coil_register",
    "get_inharmonicity_for_f0",
    "get_voice_string",
    "infer_string_names",
    "is_voice_matching_source",
    "numpy_aperture",
    "numpy_pickup_acoustic_response",
    "numpy_pickup_anti_resonance",
    "numpy_pickup_electrical_response",
    "numpy_pickup_macro_aperture",
    "numpy_position",
    "pickup_acoustic_response",
    "pickup_anti_resonance",
    "pickup_electrical_response",
    "pitch_to_note_name",
    "position_envelope",
    "resolve_pickup_electrical_deconvolution",
    "resolve_pickup_electrical_deconvolution_np",
    "resolve_pickup_electrical_response",
    "resolve_pickup_electrical_response_np",
    "resolve_scale_length",
    "resolve_scale_range",
]
