"""
Allomorph Circuit Simulation Engine
Analytical closed-form nodal RLC solver and state-space non-linear saturation.
"""

from allomorph.circuit.audio import (
    apply_prefilter_to_audio,
    find_default_input_audio,
    prefilter_audio,
)
from allomorph.circuit.parser import (
    MAGNET_PROPERTIES,
    CircuitModel,
    eval_pot_taper,
    load_circuit,
    parse_netlist,
    parse_spice_val,
)
from allomorph.circuit.saturation import (
    _HAS_NUMBA,
    _dahl_core,
    _lenz_envelope_core,
    _lenz_velocity_drag_core,
    _slew_limit_core,
    apply_dahl_hysteresis,
    apply_elliptical_orbit_projection,
    apply_oversampled_saturation,
)
from allomorph.circuit.simulation import (
    AUDIO_DIR,
    CALIBRATION_PEAK_CEILING,
    CANONICAL_SWEEP_PATH,
    FRONTENDS_DIR,
    INTERMEDIATE_TARGET_PEAK_DBFS,
    INTERMEDIATE_TARGET_RMS_DBFS,
    MODELS_DIR,
    MODELS_FRONTENDS_DIR,
    REPO_ROOT,
    TARGETS_DIR,
    _simulate_voice_task,
    simulate_circuit_audio,
    simulate_voice,
)
from allomorph.circuit.solver import (
    apply_magnet_properties_to_model,
    compute_active_preamp_eq,
    compute_circuit_transfer_functions,
    compute_core_impedance,
    compute_differential_circuit_transfer_functions,
)
from allomorph.circuit.staging import (
    _export_frontend_ir_task,
    _export_frontend_wet_wav_task,
    compute_frontend_deconvolution_fir,
    export_all_frontend_irs,
    export_all_frontend_wet_wavs,
    export_frontend_ir,
    export_frontend_wet_wav,
    generate_canonical_sweep,
    main,
    simulate_backend_targets,
)
from allomorph.circuit.sweeps import (
    ParametricSweepResult,
    compute_parametric_sweep,
)

__all__ = [
    "AUDIO_DIR",
    "CALIBRATION_PEAK_CEILING",
    "CANONICAL_SWEEP_PATH",
    "FRONTENDS_DIR",
    "INTERMEDIATE_TARGET_PEAK_DBFS",
    "INTERMEDIATE_TARGET_RMS_DBFS",
    "MAGNET_PROPERTIES",
    "MODELS_DIR",
    "MODELS_FRONTENDS_DIR",
    "REPO_ROOT",
    "TARGETS_DIR",
    "_HAS_NUMBA",
    "CircuitModel",
    "ParametricSweepResult",
    "_dahl_core",
    "_export_frontend_ir_task",
    "_export_frontend_wet_wav_task",
    "_lenz_envelope_core",
    "_lenz_velocity_drag_core",
    "_simulate_voice_task",
    "_slew_limit_core",
    "apply_dahl_hysteresis",
    "apply_elliptical_orbit_projection",
    "apply_magnet_properties_to_model",
    "apply_oversampled_saturation",
    "apply_prefilter_to_audio",
    "compute_active_preamp_eq",
    "compute_circuit_transfer_functions",
    "compute_core_impedance",
    "compute_differential_circuit_transfer_functions",
    "compute_frontend_deconvolution_fir",
    "compute_parametric_sweep",
    "eval_pot_taper",
    "export_all_frontend_irs",
    "export_all_frontend_wet_wavs",
    "export_frontend_ir",
    "export_frontend_wet_wav",
    "find_default_input_audio",
    "generate_canonical_sweep",
    "load_circuit",
    "main",
    "parse_netlist",
    "parse_spice_val",
    "prefilter_audio",
    "simulate_backend_targets",
    "simulate_circuit_audio",
    "simulate_voice",
]
